### ISSUE TITLE
Supporting selecting multiple cells and move them all at once

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#112]
I am using DeepNote. Horrible to use. I can only move one cell each time. This is killing me. 
We shall allow selecting multiple cells and move them together. 

In addition, can we support grouping cells/pods? Then we move them as a whole. This is like grouping in PPT.

**Comment by li-xin-yi** [comment]
In fact, Reactflow have already multi-selection (see https://github.com/wbkd/react-flow/issues/609), in our current version CodePod, a user can try it in two ways:

1. Press <kbd>Shift</kbd>,  use the mouse to draw a rectangle area covering those pods you want to select, like what we often do to choose multiple files on a Windows desktop, then you can drag them together.

![image](https://user-images.githubusercontent.com/10118462/205972172-7beb064e-b60c-40c6-8434-20705ccf08be.png)

2. Select one pod, press the meta key on your keyboard (for my Windows OS, that is the Win key, I don't know the corresponding key on MacOS, @lihebi can you do me a favor to confirm that?) and click on another pod at the same time, then you can drag the both two pods together. 

I can change the shortcut if you feel uncomfortable with those keys (yes, I also hate win key, which toggles the windows menu), or we can discuss how to group pods in a more flexible way, for example, assigning them with customized tags and then dragging on the tag?

**Comment by lihebi** [comment]
Option 1 works, but you have to drag over the entire node to select it. Not the best experience.

Option 2 sounds better to me. It is the`⌘ Command` key on mac. But this only works on React Flow nodes (on their website), not our Code/Scope nodes. I guess we need to set some "selected" property.

**Comment by lihebi** [comment]
@forrestbao If you try option 1, you won't like it. You have to drag over the entire node to select it.

I propose to disable option 1, and re-use the `shift` key for option 2. Because
1. The `ctrl` key does not work on mac, and the `meta` key does not work on windows. The `shift` key seems to be the best choice.
2. But the `shift` key can only be used in either option 1 or option 2, not both (https://github.com/wbkd/react-flow/discussions/2208#discussioncomment-2908766).

**Comment by li-xin-yi** [comment]
@lihebi I can check the OS first and then bind the hotkey if you need. `Shift` method may be hard to implement when considering the single-parent rule because almost all nodes are selected at the same time, I can't determine which node to drop if the rule is violated.
