### ISSUE TITLE
Creating scope over pod and pod inside scope 

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#124]
I am creating this [repo](https://app.codepod.io/repo/repo_PPpPAQ7Jwj) and then I realized it takes too long to draw scopes and drag pods into scopes. Hence, this issue. 

**Problem**

Currently, to build a hierarchy, scopes and pods must be  created independently first, and then drag a pod into a scope. This is very inconvenient. 

**Suggested change**

1. A scope is created by drawing a rectangle box, instead of a fixed size now. 
2. All pods in the rectangle region are automatically added into the scope. 
3. Pods can be created inside of a created scope by right click. The pod is then automatically added into the scope.

**Comment by senwang86** [comment]
> 3. Pods can be created inside of a created scope by right click. The pod is then automatically added into the scope.

PR #232
