### ISSUE TITLE
Code and scope connectors gone after page refreshing

### ISSUE THREAD

**Issue by fundon** [codepod-io/codepod#127]
## Before
<img width="1423" alt="Screenshot 2022-12-08 at 11 43 44 AM" src="https://user-images.githubusercontent.com/27926/206351571-1ea1aa49-949e-4975-8c22-31c55348dd40.png">

## After

<img width="1267" alt="Screenshot 2022-12-08 at 11 43 55 AM" src="https://user-images.githubusercontent.com/27926/206351603-4157ac08-2d2b-48e9-b9c6-292aeeb093b9.png">

**Comment by lihebi** [comment]
Thanks! The edges are not saved to the database yet. Will be implemented in the next few releases.

**Comment by fundon** [comment]
Yes, I told to @forrestbao, Its not a bug, its unimplemented feature.
