### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by sudongyuer** [codepod-io/codepod#150]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/76603360/207582646-e3e8c1b3-0bef-47af-938d-daf7c1afb0ad.png">
Might be this line     https://github.com/codepod-io/codepod/blob/main/api/src/resolver_repo.ts#LL17C6-L17C6

**Comment by li-xin-yi** [comment]
Attach a shell to the api container, and then run

```
npx prisma migrate dev
```

After that, restrart the api container

**Comment by sudongyuer** [comment]
> Attach a shell to the api container, and then run
> 
> ```
> npx prisma migrate dev
> ```
> 
> After that, restrart the api container

Got it , thx ~
