### ISSUE TITLE
Position to paste cells in `ctrl`-`v` way

### ISSUE THREAD

**Issue by li-xin-yi** [codepod-io/codepod#155]
It's hard to implement a paste-button in the right-click menu because modern browsers restrict the read-access to system clipboard unless user explicitly does that. I tried Jupyterlab/Jupyter notebook/Colab/Deepnote, none of them implements such a paste button across pages.

![image](https://user-images.githubusercontent.com/10118462/208291180-a415ff39-383c-4bd1-912b-ae08a8bf3dd5.png)

( A hack way (custom web MIME to serialize pod data) can be used here if insisted)

`ctrl-v` way is much easier for me to implement, and faster for users to operate.  But different from those products above, which can simply appended the pasted cell to the end of the doc or cursor in 1-D space, we need a much cleared 2-D position to put the pasted cell by default, which one should we apply?

- [ ] the current center of the canvas
- [ ] last clicked position on the pane
- [ ] below/beside the copied position (not applicable for pods copied from other pages)
- [ ] others

**Comment by li-xin-yi** [comment]
@lihebi @forrestbao 

I implemented the single code node copy-paste across repos feature in this experimental branch: https://github.com/li-xin-yi/codepod-1/tree/experimental/clipboard, tests and suggestions are welcome. This is just a simple demo to show my idea, even many `console.log` calls are remained to show what in your clipboard in each stage.

How to use it:

1. Click on the copy button on the code node you want to copy.
2. Now, if you choose to paste it on a text editor (e.g. VS code, chat input box in telegram, or any text input field), only the code itself will be pasted.
3. Now, if you choose to paste it on a Codepod canvas (no matter the current page or any other repo page, you can even use different browsers with different accounts), you can:
  - open the right-click menu, click on the paste button, the identical pod shows up in place.
  - or, make sure the pane is focused, then press `Ctrl` + `V`,   the identical pod appears in the center of current canvas view.

What is copied into the canvas:

![image](https://user-images.githubusercontent.com/10118462/208371799-64db857c-55dc-4044-8e63-65708a8c0daf.png)

1. Code content
2. Pod width
3. Pod name
4. Result/Error message/stdout (if the pod is executed), but the collaborator online can't see the output, because we keep runtime info independently.

How it works:

I use [`navigator.clipboard`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) to imitate the copy/paste button, write the `pod.content` as `text/plain` format, and serialize a more detailed info from pod object as `web text/plain`. This is a hack method (similar to [this blog](https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api/) ), because 1) modern browsers prohibit the direct read/write access to MIME-type data in clipboard for some privacy/security issue, unless in an explicit user-behavior (e.g. ctrl c/v, primitive conetxtmenu item), we can use `event.clipboardData.setData/getData` triggered by the user event without data type restriction. 2) we still don't want to expose the detailed pod object information to the user, but `text/plain` can be viewed almost everywhere, for example, if you copy anything, then open your system clipboard history (for windows user, press `win` + `v` ) you can find what you copied easily. But for a custom type (like `web text/plain`, not all application can read it as transparent. so we hide the serialized data in user's clipboard.

Known issues:

This is just an experimental demo for my idea, the implementation is still in an immature stage. Some issues I can fix and improve if you feel the idea is acceptable, while some are restricted by browsers, and I can't fix in a short time.

1. The pane is sometimes hard to focus, `ctrl-v` way may not work even if you click the pane several times. I only know a way for current users to enforce it: right-click the pane once, then use `ctrl-v`. I will add more focus-rules to listen to the paste event on the panes and fix that.
2. The clipboard write/read access may not work on some versions of Firefox (see [this](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility)). I never use Firefox, so I don't know, I tested on Chrome and Edge, both works well.
3. You can't copy a cell in `Ctrl`-`C` way now, don't worry, I defer this feature because it involves with multiple-pods copy-paste, I will implement it in the future.

**Comment by lihebi** [comment]
> (**Option 1**: ctrl-v triggers) KiCAD's auto-selection/moving solution is better

This sounds better to me as well.

> In Google Slides, pressing Ctrl-C/V will create an object slightly offset from the source AND selected

This is also useful. We could add an (**Option 2**) "Ctrl-D" action to duplicate the currently selected node(s) to a "slightly offset" position.

The above two options, plus (**Option 3**) the right-click paste menu (which pastes the node to the clicked point), should make this feature complete and great.

**Comment by lihebi** [comment]
> 1. To select an object for copying, can Ctrl-C work?

Not for now. According to Xinyi, `Ctrl-C` is temporarily disabled and left for the future to also support multiple selected nodes.

> 2. After pressing Ctrl-V, the object will be pasted to a location previously selected by a mouse click?

No. This current implementation will paste it to "the center of the screen". Let's replace this with KiCAD's approach you mentioned above.

> 3. If using the right-click menu to paste, the object will be pasted to the location where the right-click menu is activated?

Yes. And this PR already implemented this.

**Comment by lihebi** [comment]
> The pane is sometimes hard to focus, ctrl-v way may not work ... I only know a way ...: right-click the pane once, then use ctrl-v.

Yeah, this appears quite often; looks like some issues in React Flow.

> I will add more focus-rules to listen to the paste event on the panes and fix that.

Sounds like an interesting fix.

**Comment by lihebi** [comment]
> This is just an experimental demo for my idea, the implementation is still in an immature stage. Some issues I can fix and improve if you feel the idea is acceptable

I've tried PR #156, works great! This "web plain/text" trick sounds great to me. The only thing I worry about is that some firefox users need to [change their browser preferences](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility). We could provide some tips on the UI to remind users. What do you think about this tradeoff? @forrestbao 



<img width="780" alt="Screenshot 2022-12-19 at 12 36 27 PM" src="https://user-images.githubusercontent.com/4576201/208516804-167a176e-618c-4146-a261-3403a01a5a4c.png">

**Comment by li-xin-yi** [comment]
> To select an object for copying, can Ctrl-C work?

It's not implemented yet, but I can definitely do it in the future, I just feel it's a bit complicated to handle multiple selected pods at this time.

> After pressing Ctrl-V, the object will be pasted to a location previously selected by a mouse click?

For now, in that PR, I use the center of the visible canvas as the destination location, but I can replace it with the previously selected location if preferred.

> If using the right-click menu to paste, the object will be pasted to the location where the right-click menu is activated?

Yes.

> In Google Slides, pressing Ctrl-C/V will create an object slightly offset from the source AND selected. Then a user can immediately drag the copied object to a new location.

Sounds interesting, but what if the object is copied from another page and no object in this page is selected?

> Figma has a long solution on different varieties of copy-and-paste. [This is their help doc.](https://help.figma.com/hc/en-us/articles/4409078832791-Copy-and-paste-objects-in-the-canvas) In the simplest case, "Pasted objects try to maintain the same x and y positions within the destination frame relative to its position in the group or frame it was copied from." A user needs to then select the pasted object and move it to somewhere.

Sounds good, but may be not suitable in our case.

> In KiCAD, a desktop EDA suite, has a better solution. See [this YouTube video](https://youtu.be/3qPG62rsZ6Q) of mine.

Good demo video, it looks awesome, I like it too. However, I have no knowledge about EDA, so I don't know if this application supports collaborative-editting? If it does, what other online users can see before the position of the object is confirmed? A complete real-time moving track, same as the operating user? Or nothing?

**Comment by lihebi** [comment]
> [xinyi] what other online users can see before the position of the object is confirmed? A complete real-time moving track, same as the operating user? Or nothing?

I think "nothing" is good enough. We'll notify yjs collaborators when the pod is actually dropped.

**Comment by forrestbao** [comment]
> I've tried PR #156, works great! This "web plain/text" trick sounds great to me. The only thing I worry about is that some firefox users need to [change their browser preferences](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility). We could provide some tips on the UI to remind users. What do you think about this tradeoff? @forrestbao
> 
> <img alt="Screenshot 2022-12-19 at 12 36 27 PM" width="780" src="https://user-images.githubusercontent.com/4576201/208516804-167a176e-618c-4146-a261-3403a01a5a4c.png">

What does the / for "read" row and "Chrome" column mean? Does it mean there are limitations even when "reading" in Chrome?

**Comment by li-xin-yi** [comment]
> What does the / for "read" row and "Chrome" column mean? Does it mean there are limitations even when "reading" in Chrome?

Yes, it means in some older versions of Chrome, `clipboard.read()` are partially supported (i.e., only a few types can be read).

**Comment by li-xin-yi** [comment]
@lihebi @forrestbao 

Take a look at my new experimental branch, welcome to try and give me any suggestion.

PR: https://github.com/codepod-io/codepod/pull/158

vote for the rule of the initial pasted position and the anchor point in the pod!
