### ISSUE TITLE
Dummy vertical scroll bar in RichNode

### ISSUE THREAD

**Issue by li-xin-yi** [codepod-io/codepod#169]
It exists in Chrome/Edges/Firefox on my side

![image](https://user-images.githubusercontent.com/10118462/209416162-967666de-c036-4371-b378-4320b990a8c0.png)

I can't figure out how to fix it by now.

**Comment by li-xin-yi** [comment]
I doubt it is an intrinsic bug (or feature) of Remirror editor. What do you guys see from its [official story book](https://remirror.vercel.app/)?

On my side, the scroll bar is still here:

![image](https://user-images.githubusercontent.com/10118462/209422157-d074b465-e14e-45df-87f0-f2ef521bb823.png)

**Comment by lihebi** [comment]
Interesting, good to know. Thanks for investigating this. Let's ignore this issue for now.

**Comment by forrestbao** [comment]
I'd strongly recommend all of us to take a look at CloverApp.com 
Their canvas based tool is called "Surface". We have a lot to learn from them.

**Comment by lihebi** [comment]
close by #248
