### ISSUE TITLE
Markdown link syntax not supported in note pods

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#172]
**Problem** 
![image](https://user-images.githubusercontent.com/438579/209455224-6a819c59-d345-46bd-b5da-4b7845d0ca9b.png)

**Expected change**

Support link syntax of Markdown in note pods.

**Comment by senwang86** [comment]
Does PR #257 address this issue?

**Comment by lihebi** [comment]
Not yet. Markdown's link syntax (`[]()`) does not trigger Remirror's link. We need to implement it. The solution is to add a [`inputrules`](https://prosemirror.net/docs/ref/#inputrules) component to [Remirror's link extension](https://github.com/remirror/remirror/blob/3e1f7cde3cfc7fae45e0eb4c56db849fc6975c91/packages/remirror__extension-link/src/link-extension.ts#L292).

**Comment by forrestbao** [comment]
@li-xin-yi can you help with this? 

Another issue is that once Markdown becomes richtext, I cannot go back from richtext to Markdonw source.

**Comment by li-xin-yi** [comment]
I can explore it. But I searched a little just now, there is no existing markdown style link extension for it now. It seems an old problem.

see https://github.com/remirror/remirror/issues/1717
