### ISSUE TITLE
Justification and width of a scope's title

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#175]
When the title of a scope is too long, only the rightmost 20-ish characters are displayed. See below. 

![image](https://user-images.githubusercontent.com/438579/209482289-f83d3ceb-29a8-47e2-957d-f06a98d47f95.png)

We shall, 
1. increase the  width of the title
2. wrap or truncate the title if still too long, unless we prompt users how many characters are remaining (like in Twitter)

**Comment by senwang86** [comment]
PR #376 is under review.

**Comment by lihebi** [comment]
> PR #376 is under review.

These are different. This issue concerns **scope title size**, while #376 is **contextual zoom's font size**.

**Comment by forrestbao** [comment]
I think this has been fixed as of yesterday. https://github.com/codepod-io/codepod/commit/e515fd121c491e8c12f65d08bfcc73fd104cad78
