### ISSUE TITLE
auto-shovel pods/scopes that will overlap due to width/height expansion

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#176]
I am trying to use CodePod to develop a [real bioinformatics program](https://app.codepod.io/repo/dg0bns4a8yxqpvapb0ni) and I have found a series of pains. This is the first one. 

**Problem**

I spend a lot of time on manually repositioning pods or scopes. This greatly reduces my development speed. 

There are two cases: 
1. If I expand a **scope's width or height**, or **the width of a pod**, manually, pods and scopes in the way do not move away automatically. Instead, they overlap. So I have to first make space for the expansion and then expand. 
2. For a code pod, as the code gets longer (thus **the height of a pod** increases), it overlaps with pods or scopes that were originally below it. Like the case above, I have to manually find spaces again. 

**Expected change**

We do not need fancy auto-layout to solve this problem. Just do auto-shoveling. When the width (height) of a pod/scope expands, automatically push the pods/scopes in the way to the right (down), recursively, so users do not have manually make the space. 

For the scope, I really want the automatic bubbling #151 to be implemented so I can save time from manually adjusting the shape the of a scope.

**Comment by li-xin-yi** [comment]
Will a growing pod/scope push other pods nearby away, or we just let them overlap with other peers?

**Comment by forrestbao** [comment]
> Will a growing pod/scope push other pods nearby away, or we just let them overlap with other peers?

Push them away.
