### ISSUE TITLE
function undefined when using Python's `multiprocessing`

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#180]
Please go to [this repo](https://app.codepod.io/repo/dg0bns4a8yxqpvapb0ni), and then to the function `search_telomeres`. 

If you uncomment line 9 and then run pod `Main_test` you will get an error that the function `check_one_telomere` defined right to the right of `search_telomere` in the same scope is considered undefined.

**Comment by forrestbao** [comment]
The reason is probably due to function name rewriting.

**Comment by lihebi** [comment]
I'm closing this. We have fixed many things in the scoped runtime since then. This issue may be fixed already.

**Comment by forrestbao** [comment]
I don't have the original code. But it seems that the bug has been fixed.
