### ISSUE TITLE
[Discussion] Rules to jump between pods via arrow keys

### ISSUE THREAD

**Issue by li-xin-yi** [codepod-io/codepod#209]
For example, how to determine the next pod to jump when pressing <kbd> -> </kbd>.

**Comment by forrestbao** [comment]
This is easy. Have you used some TV remotes where you have only four direction keys to navigate thru a non-orthorgonal menu options? 

When `->` is pressed, just jump to the cell/scope that is to the right of the current cell/scope, but with least vertical offset. 
Similarly for other three arrow keys.

**Comment by senwang86** [comment]
PR #327.

**Comment by forrestbao** [comment]
Is this solved? The jumping earlier is only available within one scope.

**Comment by senwang86** [comment]
> Is this solved? The jumping earlier is only available within one scope.

I think issue #88 covers this one, and we can avoid some redundancy by keeping the discussion in one place.

**Comment by forrestbao** [comment]
I jus tested, the jumping is only allowed within the same scope. You cannot move out of a scope. Give it a try: https://app.codepod.io/repo/eyusr62dyglelzg7m4jz

**Comment by senwang86** [comment]
> I jus tested, the jumping is only allowed within the same scope. You cannot move out of a scope. Give it a try: https://app.codepod.io/repo/eyusr62dyglelzg7m4jz

Yes, I am aware of that. I think it's simpler to keep related issues in one place.

**Comment by forrestbao** [comment]
https://github.com/codepod-io/codepod/pull/398
