### ISSUE TITLE
Runtime shown as connected but seem not acutally

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#262]
**How to repeat** 

I sometimes leave an opened Pod repo in my browser and am away for hours. When I come back, the runtime is no longer connected -- as indicated in the side panel. So I refresh the browser tab. Then the side panel shows the runtime is connected. But when I try to run a cell, it just runs indefinitely. 

Sometimes I could fix the issue by going back to the dashboard and re-enter the repo. But this does not always work. Killing the runtime does not always fix the issue either. This is a very fruastrating bug that may negatively impact users' trust to Codepod. 

See the issue video below. 

https://user-images.githubusercontent.com/438579/236002217-16c98e68-6c2a-4e87-ba04-edd6f820da64.mp4

This might be related to issue #171

**Comment by lihebi** [comment]
This was not a runtime connection issue, but `web-tree-sitter`'s version issue causing an error when loading wasm. fixed in #263
