### ISSUE TITLE
import variables from parent scope to child scope

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#264]
I'd like to make a case for allowing importing variables to a scope from its parent scope. 

[This repo](https://app.codepod.io/repo/6ozhwnla4i96ii6gj5h4) is a working example. 

While building each function, I wanted to test it in its scope. But the functions' arugments are very complicated. So writing test cases on-the-fly will be very tedious. Hence, I wanted to import some global variables, like `docs` and `vocab` in the working example repo, into the scope where I define LDA functions and their test functions. 

Right now because I cannot import variables to a scope from its parent, I had to expose nearly all functions, even the priting functions, to the global scope and test in the global scope. This is counter-productive (because time wasted on things other than writing the code) and increase the user's mental overhead.

**Comment by lihebi** [comment]
closed by #284
