### ISSUE TITLE
Re-assigning a variable does now work.

### ISSUE THREAD

**Issue by kolibril13** [codepod-io/codepod#309]
I just want to report this issue:
This code runs in normal python
```
foo = [1,2,3]
foo[2] = 2
```
But throws an error in codepod:
<img width="599" alt="image" src="https://github.com/codepod-io/codepod/assets/44469195/cecad2ed-7ea7-47f6-9f03-b648c7551ea5">

**Comment by lihebi** [comment]
Thanks for the report! That's a bug in our parser/compiler in handling line 2. I'll get that fixed.
