### ISSUE TITLE
Trigger auto-layout when Contextual zoom is toggled on/off

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#315]
Toggling contextual zoom on or off will change the font size and thus pod/scope sizes. But auto-layout is not triggered after toggling. 

**Expected:** 
After auto-layout is toggled on or off, auto-layout should be triggered.

**Comment by chimmyten** [comment]
Hello, I've implemented auto-layout to be triggered when the auto-layout setting is toggled on in the sidebar. Is there any expected change for auto-layout activation regarding the contextual zoom setting?

**Comment by lihebi** [comment]
There should be no additional changes necessary. The auto-layout should be separate from contextual zoom.
