### ISSUE TITLE
Auto hide of output box menus

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#321]
Codepod has three menu options for the output box of a code pod, "(un)focus", "Hide", "Clear". 
They overlay with the output content (screenshot below). 

**Expected change**: 
1. The menu options should only appear when a mouse is hovered over the output box. Remain hidden when not hovered over. 
2. When they appear, they should appear above a white background to avoid the overlap that makes reading hard. 
3. It's better to lay them out vertically to minimize the overlap with the output content. 

![Screenshot 2023-05-29 02:31:44](https://github.com/codepod-io/codepod/assets/438579/18dd2619-0f64-467b-b9ac-f624ce539cbd)

**Comment by chimmyten** [comment]
Hello, it's Timmy. I'm currently working on this issue. If the menu options are laid out vertically, they will go past the output box for shorter outputs. Is it better to expand the empty space for shorter outputs to contain all menu options or leave the menu options going past the bottom of the output box?

**Comment by chimmyten** [comment]
I moved it up and slightly to the left to avoid overlap with the resizing handle. Does this look okay?
<img width="374" alt="Auto-Hide Menu Changes" src="https://github.com/codepod-io/codepod/assets/105993789/31e9f9d9-19c2-4e37-8ef9-fd91bea30ad0">

**Comment by lihebi** [comment]
Looks great.

**Comment by forrestbao** [comment]
Closed via #336
