### ISSUE TITLE
IPython module in CodePod

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#322]
I am trying to use CodePod as a notebook for AIGC, e.g., trying out different prompts to generate the images until reaching one that I like.  I used openAI's DallE. 

However, I run into an interesting issue. OpenAI's DallE API returns a string, the web URL of an image. When passing the URL to `IPython.display.Image` function, the image can be displayed. But if I wrap up the displaying code snippet into a function, the image is not displayed. 

See the screenshot below. The pod in the middle is the problematic one. The rightmost pod displays the image as expected. 

![Screenshot 2023-05-29 03:08:56](https://github.com/codepod-io/codepod/assets/438579/258d5659-a206-4f80-97c6-5ceba45754f0)

**Comment by lihebi** [comment]
You should return the Image in your function.

**Comment by forrestbao** [comment]
oh my stupidity. i forgot to return
