### ISSUE TITLE
refresh dashboard when deleting a repo

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#330]
Currently after a repo is deleted via clicking the delete button at the dashboard, nothing is displayed at the dashboard such as "deleting" nor removing the repo from the dashboard upon deletion finishes. One has to refresh the dashboard to see the repo removed. 

**Expected change**
1. Ask the user to confirm the deletion of a repo to prevent accidental removal.  
2. Show a swirling circle when deleting the repo. 
3. Remove the repo upon deletion finishes. It's better if an animation can be shown when updating the project list, e.g., move the projects below up to fill the space of the deleted repo.

**Comment by forrestbao** [comment]
#353

**Comment by sumtsui** [comment]
#364
