### ISSUE TITLE
Star ⭐ a repo 

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#414]
On the dashboard, users can favorite ⭐ a repo. Starred repos will be shown at the top of the list.

**Comment by forrestbao** [comment]
https://github.com/codepod-io/codepod/issues/367

**Comment by lihebi** [comment]
This one is slightly different. It's the "favorite" feature, not the "star" feature. It's for users to mark **their own projects**. For example, I have dozens of repos, and I need a visual way to make **important ones stand out**.

Nevertheless, the "star" and "favorite" features are implemented as a unified one.
