### ISSUE TITLE
yjs server can't connect to the new kernel

### ISSUE THREAD

**Issue by senwang86** [codepod-io/codepod#490]
The yjs and api server still try to connect the previous kernel after activating a new kernel, to reproduce, 
- create a new runtime
- delete the previous runtime
- check yjs container logging
- check api container logging 

The problem got fixed after restart yjs and api containers twice. 

<img width="1114" alt="Screenshot 2023-08-28 at 4 31 26 PM" src="https://github.com/codepod-io/codepod/assets/10226241/46df7f75-8972-46e2-9105-c880a5995c1f">

<img width="1455" alt="Screenshot 2023-08-28 at 4 30 47 PM" src="https://github.com/codepod-io/codepod/assets/10226241/81e1752f-1d76-47c8-bc83-c1a5a727f61e">

<img width="1440" alt="Screenshot 2023-08-28 at 4 39 33 PM" src="https://github.com/codepod-io/codepod/assets/10226241/b0a9eec1-0cf8-435e-b0ac-32cdbdd13fe9">

**Comment by senwang86** [comment]
Need some help to understand the [resolver_yjs.ts](https://github.com/codepod-io/codepod/blob/main/apps/api/src/resolver_yjs.ts#L12C1-L12C58) and [yjs-runtime.ts](https://github.com/codepod-io/codepod/blob/main/apps/yjs/src/yjs-runtime.ts#L144C1-L144C1).

**Comment by lihebi** [comment]
There are some leftover tasks in runtime. I'll work on that.

For now, if a runtime doesn't connect, just delete it and create a new one.
