### ISSUE TITLE
Separate spaces for Python and shell

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#544]
Jupyter has magic commands, like `!ls` 
But its variable space differs from Python's. 

So the commands below cannot work together: 

```
data_dir = "/mydata" 

!ls data_dir # or !ls $data_dir
```

**Comment by li-xin-yi** [comment]
Actually, the commands work.

On native Jupyter, you can use
```
!ls $data_dir
```

or
```
!ls {data_dir}
```

On current released Codepod (official website), you can even omit `$` or `{}`, use `!ls data_dir`

for example:

<img width="362" alt="image" src="https://github.com/codepod-io/codepod/assets/10118462/28295dd5-3911-4d37-865e-c62fa8aebe82">


```

**Comment by li-xin-yi** [comment]
Sorry, I misunderstood the problem...yes, we should prevent the evaluation of shell commands using Python runtime, unless `{}` is specified.

**Comment by lihebi** [comment]
> you can even omit `$` or `{}`, use `!ls data_dir`
> 
> for example:
> 
> <img alt="image" width="362" src="https://user-images.githubusercontent.com/10118462/267814519-28295dd5-3911-4d37-865e-c62fa8aebe82.png">

This is an interesting (maybe unwanted, or maybe useful) side-effect of the code rewriting. You are effectively running:

```
!echo s_ROOT
```

**Comment by lihebi** [comment]
> current released Codepod (official website)

A side note: the production app on the website hasn't been updated for quite a long time (1 or 2 months). There has been a lot of changes, I'll update it when wrapping up the current overhauls.

**Comment by lihebi** [comment]
> variable space differs

This is generally useful. We could support it via the planned cross-language runtime coming later this year. I.e., a python pod produces some result to be consumed by a shell pod.

**Comment by forrestbao** [comment]
Interesting, maybe it's a limitation of my local Jupyter runtime, on which I found the issue earlier. Now after I switch to Colab's native runtime, I can do

```
x="123"
!ls $x
```
