### ISSUE TITLE
Pod UI improvements

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#55]
This is how the pod UI looks like now. 
![image](https://user-images.githubusercontent.com/438579/202609763-550b74f0-1494-4fcd-9598-c4a4ac389bd9.png)

**Suggested changes** 
1. [ ] Move the top/tool bar of the pod to the top-right corner -- slightly extruding to the top, like Google CoLab's design (screenshot below). When a cell is not focused or hovered over, it should be hidden. When a cell is, display it. Just as in Google CoLab. 
    
    ![image](https://user-images.githubusercontent.com/438579/202611486-94c37d91-f792-454c-92bd-5f269d4efa2d.png)
2. [x] In the tool bar, for every icon, when hovered over, display the tooltop on top of it rather than to the right of it, which may block users from seeing or selecting the next icon. 
2. [x] The red dot is ugly. Change it to a trash can icon. 
3. [x] Align the output behavior the same as Jupyter. Do not distinguish `stdout` and `Result: [0]:`. 
4. [x] Border for a pod: 
    a. [ ] Round corner 
    b. [ ] black line to gray line. 
    c. [ ] Show shadow around the pod being edited. Currently we only shadow a pod being moved on the canvas. 
5. [x] Number the pod's order in execution. Just like in Jupyter, e.g., `In [21]: ` and `Out [21]:`. 
6. [x] If a pod was executed without error last time, show a green checker, as in DeepNote. 

Please take a look at the designs of Google Colab ([this notebook by me](https://colab.research.google.com/drive/15repLULKxghG5FYIeBbxoL-47JyGoRXI#scrollTo=Bu8IhewrNwcr)) and Deepnote ([this notebook by me](https://deepnote.com/workspace/forrest-bao-8d3a-8e96c0f9-789e-4b51-b08f-8c67f93fd301/project/NLPclass-5185c4e4-930a-4349-b76b-be1834007069/notebook/LDA-d3cd48df628e43349658499d66eb8093)).

**Comment by forrestbao** [comment]
@nibilin33 Has the auto hide of toolbars also implemented?

**Comment by forrestbao** [comment]
@pionxzh Can you work on this issue as the next step? Right now, the toolbars for all pods and scopes are displayed. This creates too much visual distraction. Please see my first checklist above. We want the toolbar of a scope to be hidden unless the pod is selected for editing or the output part is clicked. You can take a look at how DeepNote or Google CoLab handles this. Please keep the toolbar hide/show behavior consistent with theirs. 
[Here](https://colab.research.google.com/drive/15repLULKxghG5FYIeBbxoL-47JyGoRXI#scrollTo=rp1KKAoxQrGZ) is a CoLab notebook of mine. 
[Here](https://deepnote.com/workspace/forrest-bao-8d3a-8e96c0f9-789e-4b51-b08f-8c67f93fd301/project/NLPclass-5185c4e4-930a-4349-b76b-be1834007069/notebook/LDA-d3cd48df628e43349658499d66eb8093) is a Deepnote book of mine.

**Comment by senwang86** [comment]
> Move the top/tool bar of the pod to the top-right corner -- slightly extruding to the top, like Google CoLab's design (screenshot below). When a cell is not focused or hovered over, it should be hidden.

PR #234.

**Comment by forrestbao** [comment]
> Number the pod's order in execution. Just like in Jupyter, e.g., In [21]:  and Out [21]:
This is gone in current
