### ISSUE TITLE
Show call stack in error message

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#56]
**Summary**
I now run into a simple Python error. But the error tracing information does not show call stack, making debugging difficult. 

**Details**
![image](https://user-images.githubusercontent.com/438579/202619251-ee3d1556-1cac-40f3-b438-2b5c312d26c7.png)

My error was that I forgot to import a module.  But the tracking information does not show that the error is from the function `init_TA` and then from line 2 of `init_TA`. Instead, the error is from `CODEPOD_EVAL`.

**Expected change**
Please print standard call stack for tracing bugs.

**Comment by lihebi** [comment]
Yes, this is fixed. This is from the old language-dependent scoped runtime.
