### ISSUE TITLE
Bug: the output index from runtime kernel seems to be always [0]

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#65]
This is a known bug long time ago; fix should be easy.

**Comment by forrestbao** [comment]
This is bug solved?

**Comment by forrestbao** [comment]
Even in a nest 2D structure, users may still wanna see the order that pods are executed?
What are the benefits to remove it?

**Comment by lihebi** [comment]
There seems to be a long time misunderstanding here. @li-xin-yi  was talking about the **creation order**, and we don’t need that. This issue is about **output** index, yes we need it.

**Comment by lihebi** [comment]
<img width="400" src="https://user-images.githubusercontent.com/4576201/206838396-1a52f929-7884-48af-82b7-3b4756c76392.jpg"/>

**Comment by forrestbao** [comment]
Clear!
