### ISSUE TITLE
Overflow in right-anchored output 

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#66]
The bottom of the output exceed the bottom of output box. 

![image](https://user-images.githubusercontent.com/438579/202900189-0d8369b3-6eb5-40b3-ab83-2138d3907305.png)

![image](https://user-images.githubusercontent.com/438579/202900016-72a8436c-a217-471a-b0a8-506eba0871c9.png)

**Comment by nibilin33** [comment]
done https://github.com/codepod-io/codepod/pull/62/commits/2d163b8ead79b524a358725dee27579e0a3f77d4
