### ISSUE TITLE
Log-in page by default for users not logged in

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#77]
**Problem**

Currently, if a user is not logged in, s/he sees a blank dashboard. S/he has to take an extra step to click the "Login" menu to log in. 

![image](https://user-images.githubusercontent.com/438579/203264122-fe8cec9b-0f79-4b55-94c6-0bd3ba54af61.png)

**Changes to be made**

If browser has no log in info, then bring up the log-in page automatically.

**Comment by li-xin-yi** [comment]
Re-assign it to me, please. I'm also fixing the unauthenticated issue mentioned in https://github.com/codepod-io/codepod/pull/81 these dayas.
