### ISSUE TITLE
keyboard short cut to move focus/editing to a new cell

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#87]
Can we allow programmers to move the  focus/editing from one cell to another using keyboard shortcuts on top of mouse operations? 

In Jupyter, it was easy, just quit Edit mode into Command mode and then use up and down arrow keys to move between cells. Maybe we should simply use up, down, left, and right arrows. But we need to first  enable Edit and Command modes (#88) .

**Comment by forrestbao** [comment]
@pionxzh

**Comment by forrestbao** [comment]
The hopping between cells via keyboard operations has been done in https://github.com/codepod-io/codepod/pull/327 
But we still need the keyboard shortcut to switch between edit mode and command mode. https://github.com/codepod-io/codepod/issues/88

**Comment by senwang86** [comment]
Please refer PR #398.
