### ISSUE TITLE
Google doc style repo creation

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#91]
Currently, one must give a name when creating a repo. This creates an extra barrier for users to get started.

On GitHub, each project has a handle, e.g. `codepod-io/codepod`. We won't use that. Instead, we use Google Docs's approach. Users can create a repo, and it will be titled "Untitled". We can have many "Untitled" repos, no need to be unique (but they will have unique hash ID). The title can be edited at any time.

For reference, this is Google Docs interface:

<img width="484" alt="Screenshot 2022-11-23 at 11 48 27 PM" src="https://user-images.githubusercontent.com/4576201/203723676-99518484-b664-4863-aa3f-332433b6b255.png">

**Comment by lihebi** [comment]
@forrestbao Any input on this?

**Comment by lihebi** [comment]
"If we don't have a handle like `torvalds/linux`, how should we share/discover/refer-to?" One would ask.

Easy; everyone is Youtuber here. You have a customizable homepage to showcase your work, and each of your project has a short unique URL like https://youtu.be/Npu7jkJk5nM

<img width="1176" alt="Screenshot 2022-11-23 at 11 52 51 PM" src="https://user-images.githubusercontent.com/4576201/203724791-84fd7214-7cd4-48ac-9083-79d0b9773f6d.png">

**Comment by forrestbao** [comment]
I think a better analogy is Google CoLab. In Google Colab, once you create a notebook, the default name is `untilted.ipynb`. Then you can changed it as in Google Docs. 
Yeah, I like this idea. 

On a related note, we can also remove "private" switch when creating a notebook. Just let a notebook by default be private until a user chooses to share it. 

Then, on yet another related note, "share" means "public"? What about team share? We shall follow Google Docs sharing scheme

![image](https://user-images.githubusercontent.com/438579/203876269-c8f80fd7-6085-4280-9879-b5f71c8d3c6c.png)

**Comment by forrestbao** [comment]
> "If we don't have a handle like `torvalds/linux`, how should we share/discover/refer-to?" One would ask.
> 
> Easy; everyone is Youtuber here. You have a customizable homepage to showcase your work, and each of your project has a short unique URL like https://youtu.be/Npu7jkJk5nM


You can take a look at how DeepNote does it. For example, 

https://deepnote.com/workspace/forrest-bao-8d3a-8e96c0f9-789e-4b51-b08f-8c67f93fd301/project/NLPclass-5185c4e4-930a-4349-b76b-be1834007069/notebook/LDA-d3cd48df628e43349658499d66eb8093  

It contains user name, workspace name, and notebook name. But adds a hash behind all three. I think this is to prevent name changes. However, I think the hash is too long. It defeats the purpose to include names at all. 

Or you can take a look at Twitter. 

https://twitter.com/forrestbao/status/1595900998131793920 

It still has the username and uses a unique tweet ID for posts.

**Comment by forrestbao** [comment]
I think Using hashes or integers is very bad idea. The link is too long. YouTube does a better job by using a-z, A-Z and then 0-9. We should do that.

**Comment by lihebi** [comment]
> username and uses a unique tweet ID

Including userid and repoid sounds good.

> YouTube does a better job by using a-z, A-Z and then 0-9. We should do that.

We used [nanoid](https://github.com/ai/nanoid) with [nolookalikes](https://github.com/CyberAP/nanoid-dictionary#nolookalikes), it generates something like this: `Y8WCEGKQjH`.

https://github.com/codepod-io/codepod/blob/58aea55c1e430a5befcd7043f296c8cd011a43ac/ui/src/pages/repos/CreateRepoForm.tsx#L16-L18
