### ISSUE TITLE
UI improvements for scope boxes 

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#98]
I suggest
1. Change the header bar to what pod's look like. No explicit header bar like in Windows 95. No red dot. 
2. Do not use pink infill. Use light blue.
3. Add a delete button. Once clicked, it will remove the scope box. 

@lihebi @nibilin33 what do you say?

**Comment by lihebi** [comment]
Sounds good.

**Comment by forrestbao** [comment]
@nibilin33 Please work on this when you have time.

**Comment by nibilin33** [comment]
to make it look like this?
![20221129204125](https://user-images.githubusercontent.com/20850940/204533068-fb1b19de-f011-4bf2-8274-f55cb20fe194.jpg)

**Comment by forrestbao** [comment]
Please keep the name scope in the head though. Need to distinguish a scope from a code cell. 
@lihebi What's your opinion?

**Comment by lihebi** [comment]
We probably need to involve a designer here.
