### ISSUE TITLE
Cannot move pod out of a scope

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#99]
Currently we cannot move a pod/scope out of a scope to dissociate a child pod/scope from a parent scope. This is very inconvenient and it looks stupid when we demo to investors.

**Comment by lihebi** [comment]
First, the current pod-cannot-be-moved-out behavior is useful (i.e., the [`extent: 'parent'`](https://reactflow.dev/docs/api/nodes/node-options/#extent), e.g., the [node B.1 in this example](https://reactflow.dev/docs/examples/layout/sub-flows/)).

We do want to move a pod out. We could probably add a "release button", which, once clicked, temporarily removes the `extent: 'parent'` field to allow it to be moved out.

**Comment by sudongyuer** [comment]
if we just removes the `extent: 'parent' ` , the node's parent still exist , shouldn't we consider removing its parent node?

**Comment by sudongyuer** [comment]
I have already change the pr ( use a button to control the extent option )  #143
